Map<String, String> english = {
  'Pushed': 'You have pushed the button this many times:',
  'ChangeLanguage': 'Change Language',
  'PressMe': 'Press Me',
  'Valid': 'Valid',
  'Invalid': 'Invalid',
  'Phone': 'Phone number',
  'NewToApp': 'New to app?',
  'Password': 'Password',
  'Email': 'Email',
  'Login': 'Login',
  'Register': 'Register',
  'FullName': 'Full Name',
  'ConfirmPassword': 'Confirm Password',
  'User': 'User',
  'Specialist': 'Specialist',
  'AlreadyHaveAccount': 'Already have account?',
  'CreateNewAccount': 'Create New Account',
  'Thisfieldrequired': 'This field required',
  'NewEmail':'New Email',
  'Change':'Change',
  'OldPassword':'OldPassword',
  'NewPassword':'NewPassword',
  'Change Password':'Change Password',
  'Change Email':'Change Email',
  'NewPhone':'New Phone',
  'Change Phone':'Change Phone',
  'Search':'Search',
};
